<!doctype html>

<html lang="nl">
	<head>
		<meta charset="utf-8" />
		<?php if(isset($project)): ?>
		<title>Mediacollege Expo &middot; <?php echo $project->getName(); ?></title>
		<link rel="stylesheet" type="text/css" href="/expo/assets/css/style.css">
		<script language="JavaScript" src="/expo/assets/scripts/project.js"></script>
		<?php else: ?>
		<title>Mediacollege Expo</title>
		<?php endif; ?>
		<link rel="stylesheet" type="text/css" href="/expo/assets/css/base.css">
	</head>
	<body>
