<!doctype html>
<html lang="nl">
	<head>
		<meta charset="utf-8" />
		<link rel="stylesheet" href="/expo/assets/css/base.css">
		<?php if(isset($project)): ?>
		<title>Mediacollege Expo &middot; <?php echo $project->getName(); ?></title>
		<link rel="stylesheet" href="/expo/assets/css/project.css">
		<?php else: ?>
		<title>Mediacollege Expo</title>
		<link rel="stylesheet" href="/expo/assets/css/landing.css">
		<?php endif; ?>
	</head>
	<body>
