<?php

require_once('templates/helpers/blocklayout.php');
$blocks = generateMap();

use Expo\Session as Session;

?>
<h2><span class="ma">M</span>ediacollege <span class="ma">E</span>xpo</h2>
<div id="grid">
<ul>
	<?php foreach($blocks as $block): ?>
	<li class="block-<?php echo $block['size']; ?>"
		style="left: <?php echo $block['xOffset'] . 'px;' . (!isset($block['url']) ? ' background-image: url(\'' . $block['image'] . '\');' : ''); ?> top: <?php echo $block['yOffset']; ?>px;">
			<?php
			if(isset($block['url']))
			{
				echo '<a href="' . $block['url'] . '" style="background-image: url(\'' . $block['image'] . '\');"></a>';
			}
			?>
	</li>
	<?php endforeach; ?>
</ul>
</div>
<footer class="table">
	<?php
		$groups = Session::get('groupStorage')->getGroups();
		while($groups)
		{
			echo '<div class="row">';

			$columnSize = count($groups) < 4 ? count($groups) : 4;
			for($i = 0; $i < ($columnSize ? $columnSize : 4); $i++)
			{
				$group = array_shift($groups);
				echo "<div class=\"cell column-{$columnSize}\"><div class=\"group\"><span class=\"bold\">";
				echo $group->getName() . ':</span> ';

				$members = $group->getMembers();
				foreach($members as $member)
				{
					echo $member->getName() . (end($members) != $member ? ', ' : '');
				}
				echo "</div></div>";
			}

			echo '</div>';
		}
	?>
</footer>
<div id="overlay"></div>
<script src="assets/scripts/landing.js"></script>